Fixed Bugs and Update README

diff --git a/vm_clean b/vm_clean
--- a/vm_clean
+++ b/vm_clean
@@ -3,17 +3,17 @@
 # (https://google-styleguide.googlecode.com/svn/trunk/shell.xml)
 # Author: Huiyugeng
 
-BASE=/opt/vm
+VM_BASE=/opt/vm
 
 VM_NAME=$1
 CLEAN_IMAGES=$2
 
-VM_PATH=$BASE/$VM_NAME
+VM_PATH=$VM_BASE/$VM_NAME
 
 PKG_LIST=("virsh")
 
 for PKG in ${PKG_LIST[@]}; do
-    which $PKG
+    which $PKG > /dev/null
     if [ $? == 0 ]; then
         echo "$PKG already installed"
     else
@@ -22,23 +22,31 @@ for PKG in ${PKG_LIST[@]}; do
     fi
 done
 
-virsh destroy $VM_NAME
+virsh domstate $VM_NAME > /dev/null
 if [ $? == 0 ]; then
-    echo "$VM_NAME destroy successful"
-else
-    echo "$VM_NAME destroy fail"
-    exit 1
+    STATE=$(virsh domstate $VM_NAME)
+    if [ "$STATE" = "running" ] || [ "$STATE" = "paused" ]; then
+        virsh destroy $VM_NAME
+        if [ $? == 0 ]; then
+            echo "$VM_NAME destroy successful"
+        else
+            echo "$VM_NAME destroy fail"
+            exit 1
+        fi
+    fi
+
+    virsh undefine $VM_NAME
+    if [ $? == 0 ]; then
+        echo "$VM_NAME undefine successful"
+    else
+        echo "$VM_NAME undefine fail"
+        exit 1
+    fi
 fi
 
-virsh undefine $VM_NAME
-if [ $? == 0 ]; then
-    echo "$VM_NAME undefine successful"
-else
-    echo "$VM_NAME undefine fail"
-    exit 1
-fi
 
-if [ $CLEAN_IMAGES = "--with-images" ]; then
+
+if [ "$CLEAN_IMAGES" = "--with-images" ]; then
     rm -rf $VM_PATH
     if [ ! -d $VM_PATH ]; then
         echo "$VM_NAME images remove successful"
